// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVcp3o0o2bhMUMn3LNkYC1cWY3OS0RJk',
    appId: '1:18205523276:web:250d665fc26304048c63e9',
    messagingSenderId: '18205523276',
    projectId: 'food-delivery-app-cbc66',
    authDomain: 'food-delivery-app-cbc66.firebaseapp.com',
    storageBucket: 'food-delivery-app-cbc66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUUnTh5kVPgN8dad_OGnukUAUrR4sd8k',
    appId: '1:18205523276:android:b371f989e1c4c5d38c63e9',
    messagingSenderId: '18205523276',
    projectId: 'food-delivery-app-cbc66',
    storageBucket: 'food-delivery-app-cbc66.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKVcp3o0o2bhMUMn3LNkYC1cWY3OS0RJk',
    appId: '1:18205523276:web:88859dd55075998a8c63e9',
    messagingSenderId: '18205523276',
    projectId: 'food-delivery-app-cbc66',
    authDomain: 'food-delivery-app-cbc66.firebaseapp.com',
    storageBucket: 'food-delivery-app-cbc66.firebasestorage.app',
  );
}
